[package]
name = "spike-widget-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.55"
quote = "1.0.35"
ratatui = "0.26.1"
crossterm = "0.27.0"
color-eyre = "0.6.3"
proc-macro2 = "1.0.79"
itertools = "0.12.1"
